"""Common error messages."""

ERROR_GENERIC = "❌ Xatolik yuz berdi! Iltimos, qaytadan urinib ko'ring."
ERROR_USER_NOT_FOUND = "❌ Foydalanuvchi topilmadi!"
ERROR_ADMIN_ONLY = "❌ Bu faqat adminlar uchun!"
ERROR_RATE_LIMIT = "⚠️ Juda ko'p so'rov! Biroz kuting."
ERROR_NO_BALANCE = "❌ Balansingizda yetarli mablag' yo'q!"
ERROR_BLOCKED_USER = "❌ Sizning akkauntingiz bloklangan. Admin bilan bog'laning."
ERROR_INVALID_PHONE = "❌ Telefon raqami noto'g'ri formatda!"
ERROR_PHONE_EXISTS = "❌ Bu telefon raqami allaqachon ishlatilgan!"
ERROR_INVALID_AMOUNT = "❌ Miqdor noto'g'ri!"
ERROR_PROMOCODE_NOT_FOUND = "❌ Promokod topilmadi!"
ERROR_PROMOCODE_EXPIRED = "❌ Promokod muddati tugagan!"
ERROR_PROMOCODE_USED = "❌ Bu promokod allaqachon ishlatilgan!"
ERROR_SELF_PROMOCODE = "❌ O'z promokodingizni ishlatib bo'lmaydi!"

SUCCESS_GENERIC = "✅ Muvaffaqiyatli!"
SUCCESS_BALANCE_ADDED = "✅ Balans qo'shildi!"
SUCCESS_BALANCE_SUBTRACTED = "✅ Balans ayirildi!"
SUCCESS_PROMOCODE_USED = "✅ Promokod ishlatildi!"
SUCCESS_REGISTERED = "✅ Ro'yxatdan o'tdingiz!"
SUCCESS_SUBSCRIBED = "✅ Obuna bo'ldingiz!"

WAIT_MESSAGE = "⏳ Iltimos, biroz kuting..."
